### ISSUE TITLE
Previous Extent button

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#353] opened 2016-03-30 17:27 UTC
Might consider a previous extent button. It is easy to be panning around map while sitting in another location and then accidentally hit the GPS button instead of the pending activities or saved records buttons, etc.
Edit: Map automatically pans to current location after being redirected to the sync screen.

**Comment by jhudsonWA** [comment] 2016-03-30 18:31
Will evaluate for 2.0

**Comment by jhudsonWA** [comment] 2019-02-05 20:54
Closing per @joeschmit. The issue is any small change would become the previous extent. Will reopen if we get more user requests.

**Closed as completed by jhudsonWA** 2019-02-05 20:54 UTC
Labels: innovation, enhancement, iOS
