### ISSUE TITLE
Details text in History tab cut off in iOS

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#641] opened 2016-11-16 00:16 UTC
Looking at history of cable barrier record and noticed that when you look at the details of a 2411 - Inspection record that some of the questions are cut off. Not sure if this has affected any other feature activities.

![hats_textcutoff](https://cloud.githubusercontent.com/assets/16247034/20329570/eecfdaa8-ab4d-11e6-95e0-cf55c90bd81c.PNG)

![cablebarrierqanda](https://cloud.githubusercontent.com/assets/16247034/20329686/ad301184-ab4e-11e6-99d1-3e4c6620980f.JPG)

**Comment by jhudsonWA** [comment] 2016-11-16 00:25
It looks like it's a string parsing error at the ', wonder if it is the sync code or the display code. I'll take a further look.

**Comment by jhudsonWA** [comment] 2016-11-16 01:14
A fix is checked in. We would need to deploy a 2.2.2 release to fix. The problem is I assumed that the xml parser code I was using from the iOS sdk would read the enter question string, but apparently according to a support document on Apple's site that is not guaranteed, so sometimes questions would get broken up into multiple reads but only the last read would be captured (second half of the question). 

![screen shot 2016-11-15 at 5 09 38 pm](https://cloud.githubusercontent.com/assets/702446/20330912/bb0299d2-ab56-11e6-9b8e-61fbdbb372e5.png)

**Comment by jhudsonWA** [comment] 2016-11-16 01:16
And since we are going to have a release a new release I noticed these questions are out of order. I'll attempt a fix for that as well.

**Comment by jhudsonWA** [comment] 2016-11-16 02:19
Sort order bug fix. That was a fun one that's been there since the beginning. 👍 
![simulator screen shot nov 15 2016 6 17 20 pm](https://cloud.githubusercontent.com/assets/702446/20332382/250ce180-ab60-11e6-8ac4-d83f6b4aa2ef.png)

**Comment by jhudsonWA** [comment] 2016-11-17 01:56
I'll create a 2.2.2 rc soon for test of these. Small fixes so safe to just test against prod

**Closed as completed by jhudsonWA** 2016-11-17 01:56 UTC
Labels: bug, iOS
