### ISSUE TITLE
Ability to add activity in creating new feature process

### ISSUE THREAD

**Issue by kechinn** [WSDOT/HATS#351] opened 2016-03-30 17:00 UTC
During that process of adding a new feature to map, it would be useful to have option to attach an activity directly after hitting "Save Feature" button rather than closing out new feature button, activating Identify button, find and select new feature. Otherwise, the new feature can be difficult to relocate in the case it is surrounded by multiple other features. Eliminate need for multiple steps, less buttons.

**Comment by jhudsonWA** [comment] 2016-03-30 18:33
Agreed. Could at least ask the user if they want to do a record. We didn't do this by design for earlier versions. Users use to just create a new feature every time, however the workflow is different in this iPad version than it was in the old pad's so it's probably safe.

**Comment by jhudsonWA** [comment] 2016-08-08 18:06
@kechinn still needed? Please discuss with team

**Comment by jhudsonWA** [comment] 2018-10-11 19:55
No updates on this one in two years. Closing. We can always re-open if needed.

**Closed as completed by jhudsonWA** 2018-10-11 19:55 UTC
Labels: innovation, enhancement, iOS
