### ISSUE TITLE
HATS Web Analytics 

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#577] opened 2016-08-15 23:54 UTC
Ability to gather and track data relating to how our customers are using HATS Web, it'd be nice to know what reports are being ran, by user and date/time.  At one point I saw a tool that tracked in a heat map fashion how users we navigating through the site, this could be useful data for UI enhancements etc.

**Comment by sheppamwsdot** [comment] 2020-01-23 23:18
Duplicate of #827

**Closed as completed by sheppamwsdot** 2020-01-23 23:18 UTC
Labels: web
