### ISSUE TITLE
HATS Web: Current Records Not Displaying Record Data

### ISSUE THREAD

**Issue by joeschmit** [WSDOT/HATS#774] opened 2017-07-17 19:47 UTC
Hey Guys >

HATS Web > Feature Activities > Current Records > MAP Field > Any Activity > View/Edit > Boom! Only showing attachments, not showing any form data, no fields, just blankish.

**Comment by jhudsonWA** [comment] 2017-07-17 19:50
I’m on it.
On Jul 17, 2017, at 12:47 PM, Joe Schmit <notifications@github.com<mailto:notifications@github.com>> wrote:


Assigned #774<https://github.com/WSDOT/HATS/issues/774> to @jhudsonWA<https://github.com/jhudsonwa>.

**Comment by brianblood** [comment] 2017-07-17 19:51
Groovy.

**Comment by jhudsonWA** [comment] 2017-07-17 23:01
We have a script that will "fix" these records. The issue is the form version id is not being set, but it does appear to be sent up from the device. I added some extra logging to see where/if the id is getting cleared out somewhere. Once I find and fix the issue we will run the fix script.

**Comment by jhudsonWA** [comment] 2017-07-18 00:26
The bug causing this has been fixed. I'll run the script that will fix the record next. This would of affected any recored created from a pending activity on the iPad after the new form editor was released. Surprised it didn't get brought up earlier. :)

**Comment by jhudsonWA** [comment] 2017-07-18 00:32
Should be fixed.

**Closed as completed by jhudsonWA** 2017-07-18 00:32 UTC
Labels: bug, web
